# Generated by Django 3.2.4 on 2023-10-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron', '0003_cronjoblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjoblock',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
